import React, { useState, useEffect } from "react";
import "../Home/Home.scss";
import { useParams, useNavigate } from "react-router-dom";

// MATERIAL UI IMPORTS
import Card from "@mui/material/Card";
import CardActions from "@mui/material/CardActions";
import CardContent from "@mui/material/CardContent";
import CardMedia from "@mui/material/CardMedia";
import Button from "@mui/material/Button";
import Typography from "@mui/material/Typography";
import Sidenav from "../Sidenav/Sidenav";
import Topnav from "../Topnav/Topnav";
import Footer from "../Footer/Footer";

const Clothes = () => {
    const [index, setIndex] = useState(0);

    const handleSelect = (selectedIndex, e) => {
      setIndex(selectedIndex);
    };
  
    let navigate = useNavigate();
  
    const gotoProduct = () => {
      navigate("/product");
    };
    const gotoCart = () => {
      navigate("/cart");
    };
    useEffect(() => {
      window.scrollTo(0, 0);
    }, []);



    const allProduct = [
        {
          id: 1,
          primary: "Brunch this week?",
          secondary:
            "I'll be in the neighbourhood this week. Let's grab a bite to eat",
          person: "/static/images/avatar/5.jpg",
          price: "2,000",
        },
        {
          id: 2,
          primary: "Birthday Gift",
          secondary: `Do you have a suggestion for a good present for John on his work
            anniversary. I am really confused & would love your thoughts on it.`,
          person: "/static/images/avatar/1.jpg",
          price: "7,000",
        },
        {
          id: 3,
          primary: "Recipe to try",
          secondary:
            "I am try out this new BBQ recipe, I think this might be amazing",
          person: "/static/images/avatar/2.jpg",
          price: "2,700",
        },
        {
          id: 4,
          primary: "Yes!",
          secondary: "I have the tickets to the ReactConf for this year.",
          person: "/static/images/avatar/3.jpg",
          price: "32,000",
        },
        {
          id: 5,
          primary: "Doctor's Appointment",
          secondary:
            "My appointment for the doctor was rescheduled for next Saturday.",
          person: "/static/images/avatar/4.jpg",
          price: "12,730",
        },
        {
          id: 6,
          primary: "Discussion",
          secondary: `Menus that are generated by the bottom app bar (such as a bottom
            navigation drawer or overflow menu) open as bottom sheets at a higher elevation
            than the bar.`,
          person: "/static/images/avatar/5.jpg",
          price: "1,349",
        },
        {
          id: 7,
          primary: "Summer BBQ",
          secondary: `Who wants to have a cookout this weekend? I just got some furniture
            for my backyard and would love to fire up the grill.`,
          person: "/static/images/avatar/1.jpg",
          price: "50",
        },
      ];
  return (
<div>
      <h5 className="trending">Clothes</h5>

      <hr />
      <div className="stores-cont">
        {allProduct.map((allProduct) => {
          const { id, primary, secondary, price } = allProduct;
          return (
            <div className="each-product">
              <Card
                onClick={(e) => gotoProduct()}
                sx={{ maxWidth: 225, cursor: "pointer" }}
              >
                <CardMedia
                  component="img"
                  height="140"
                  image="https://images.unsplash.com/photo-1521330784804-5f69f8a17b1d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8cG9sb3N8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60"
                  alt="green iguana"
                />
                <CardContent>
                  <Typography gutterBottom variant="h5" component="div">
                    {primary}
                  </Typography>

                  <Typography variant="body2" color="text.secondary">
                    {secondary}
                  </Typography>

                  <Typography gutterBottom variant="h6" component="div">
                    &#8358; {price}
                  </Typography>
                </CardContent>
              </Card>
              <CardActions>
                <Button
                  onClick={(e) => gotoCart()}
                  size="small"
                  variant="contained"
                >
                  Add to cart
                </Button>
              </CardActions>
            </div>
          );
        })}
      </div>
    </div>
  )
}

export default Clothes